# Configuration for activation-service application

# iSHARE Client configuration
client:
  # Client ID
  id: "EU.EORI.NLPACKETDEL"
  # Client key (PEM private key)
  key: <pdc-private-key>
  # Client certificate (PEM certificate chain)
  crt: <pdc-certs>

# Configuration of database
db:
  # Use sqlite file database
  useFile: "as.db"
  # Use URI to external DB (e.g., MySQL, PostgreSQL)
  #useURI: ""
  # Enable tracking of modifications
  modTracking: false
  # Enable SQL logging to stderr
  echo: true

# Configuration of iSHARE authorisation registry
ar:
  # Endpoint for token request
  token: "https://ar.packetdelivery.net/connect/token"
  # Endpoint for create policy requests
  policy: "https://ar.packetdelivery.net/policy"
  # Endpoint for delegation requests
  delegation: "https://ar.packetdelivery.net/delegation"
  # EORI of AR
  id: "EU.EORI.NLPACKETDEL"

