# Configuration for activation-service application

# iSHARE Client configuration
client:
  # Client ID
  id: "EU.EORI.NLPACKETDEL"
  # Client key (PEM private key)
  key: <pdc-private-key>
  # Client certificate (PEM certificate chain)
  crt: <pdc-certs>

# Configuration of database
db:
  # Use sqlite file database (make sure that the volume is writeable)
  #useFile:
  #  # Filename for DB SQLite file
  #  filename: "as.db"
  #  # If empty, will use app base path
  #  filepath: ""
  # Use sqlite in-memory database
  useMemory: true
  # Use URI to external DB (e.g., MySQL, PostgreSQL)
  #useURI: ""
  # Enable tracking of modifications
  modTracking: false
  # Enable SQL logging to stderr
  echo: true

# Configuration of iSHARE authorisation registry
ar:
  # Endpoint for token request
  token: "https://ar.packetdelivery.net/connect/token"
  # Endpoint for create policy requests
  policy: "https://ar.packetdelivery.net/policy"
  # Endpoint for delegation requests
  delegation: "https://ar.packetdelivery.net/delegation"
  # EORI of AR
  id: "EU.EORI.NLPACKETDEL"

# Configuration specific to Trusted Issuer List /issuer endpoint
issuer:
  # clientId parameter
  clientId: "some-id"
  # Provider DID
  providerId: "did:key:some-key"
  # URI of Trusted Issuers List service
  tilUri: "http://til.internal"
  # URI of verifier
  verifierUri: "https://verifier.packetdelivery.net"
  # samedevice flow path
  samedevicePath: "/api/v1/samedevice"
  # JWKS path
  jwksPath: "/.well-known/jwks"
  # Allowed algorithms for JWT signatures
  algorithms:
    - "ES256"
  # Roles config
  roles:
    # Role for creating trusted issuer
    createRole: "CREATE_ISSUER"
